/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Control.ControlCategoria;
import Control.ControlProducto;
import Modelo.Categoria;
import Modelo.Producto;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author juanch0x
 */
public class CrearProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearProducto
     */
    public CrearProducto() throws ClassNotFoundException {
        initComponents();
        
               
         List <Categoria> lista = new ArrayList();
        ControlCategoria controlcategoria = new ControlCategoria();
        lista = controlcategoria.buscarCategoria();
        categoria_combo.removeAllItems();
        for (int i = 0; i < lista.size(); i++) { 
            categoria_combo.addItem(lista.get(i).getCategoria());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombre_label = new javax.swing.JLabel();
        codigo_label = new javax.swing.JLabel();
        nombre_jfield = new javax.swing.JTextField();
        codigo_jfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        boton_agregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        preciov_jfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        precioc_jfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        categoria_combo = new javax.swing.JComboBox();

        setClosable(true);
        setTitle("Crear Producto");

        nombre_label.setText("Nombre del Producto");

        codigo_label.setText("Codigo de Barras");

        nombre_jfield.setToolTipText("Tooltip");

        codigo_jfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigo_jfieldKeyTyped(evt);
            }
        });

        jLabel1.setText("Si el producto a agregar no contiene codigo de barras, se deberá dejar en blanco");

        boton_agregar.setText("Agregar");
        boton_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_agregarActionPerformed(evt);
            }
        });

        jLabel2.setText("Precio Venta");

        preciov_jfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                preciov_jfieldKeyTyped(evt);
            }
        });

        jLabel3.setText("Precio de Costo");

        precioc_jfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                precioc_jfieldKeyTyped(evt);
            }
        });

        jLabel4.setText("Categoria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(boton_agregar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre_label)
                            .addComponent(codigo_label)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(preciov_jfield)
                            .addComponent(nombre_jfield)
                            .addComponent(codigo_jfield)
                            .addComponent(precioc_jfield)
                            .addComponent(categoria_combo, 0, 179, Short.MAX_VALUE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_label)
                    .addComponent(nombre_jfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigo_label)
                    .addComponent(codigo_jfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(precioc_jfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(preciov_jfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(categoria_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(boton_agregar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_agregarActionPerformed

    //Se valida que no halla ningun campo vacio    
        
    if(preciov_jfield.getText().trim().isEmpty()||precioc_jfield.getText().trim().isEmpty()||nombre_jfield.getText().trim().isEmpty()||codigo_jfield.getText().trim().isEmpty()){
               JOptionPane.showMessageDialog(this, "Hay algun campo vacio, Todos son obligatorios.");
     }
       
    //Empieza la ejecución normal
    
               else{
        
       Producto p = new Producto();
       
      p.setNombre(nombre_jfield.getText());
      p.setPrecio_c(Float.parseFloat(precioc_jfield.getText()));
      p.setPrecio_v(Float.parseFloat(preciov_jfield.getText()));
      
       
      if(codigo_jfield.getText().equals("")){
          p.setCodigo(0);
      }else{
      
          p.setCodigo(Long.parseLong(codigo_jfield.getText()));
          
      }    
      
    // Busco el id categoría y lo seteo al objeto
        
        Categoria categoria= new Categoria();
        ControlCategoria c = new ControlCategoria();
              
        
        try {
            categoria=c.busqueda(String.valueOf(categoria_combo.getSelectedItem()));
            // a.setCategoria(String.valueOf(categoria_combo.getSelectedItem()));
        } catch (SQLException ex) {
            Logger.getLogger(CrearProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        p.setId_categoria(categoria.getId_categoria());
        
       ControlProducto e = new ControlProducto();
        try {
            e.CrearProducto(p);
        } catch (SQLException ex) {
            Logger.getLogger(CrearProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Vaciando los campos después de agregar el producto
        
        nombre_jfield.setText("");
        precioc_jfield.setText("");
        preciov_jfield.setText("");
        codigo_jfield.setText("");
       
        }
      
    
       
        
    }//GEN-LAST:event_boton_agregarActionPerformed

    private void preciov_jfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_preciov_jfieldKeyTyped
 
        //Validación sólo decimales
        
        char caracter = evt.getKeyChar();
                if(((caracter < '0') || (caracter > '9')) && (caracter != KeyEvent.VK_BACK_SPACE)
                                && (caracter !='.')){
 
                evt.consume();
                }
    }//GEN-LAST:event_preciov_jfieldKeyTyped

    private void precioc_jfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioc_jfieldKeyTyped

         //Validación sólo decimales
        
        char caracter = evt.getKeyChar();
                if(((caracter < '0') || (caracter > '9')) && (caracter != KeyEvent.VK_BACK_SPACE)
                                && (caracter !='.')){
 
                evt.consume();
                }
    }//GEN-LAST:event_precioc_jfieldKeyTyped

    private void codigo_jfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigo_jfieldKeyTyped
 //Validación sólo decimales
        
        char caracter = evt.getKeyChar();
                if(((caracter < '0') || (caracter > '9')) && (caracter != KeyEvent.VK_BACK_SPACE)){
 
                evt.consume();
                }
    }//GEN-LAST:event_codigo_jfieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_agregar;
    private javax.swing.JComboBox categoria_combo;
    private javax.swing.JTextField codigo_jfield;
    private javax.swing.JLabel codigo_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre_jfield;
    private javax.swing.JLabel nombre_label;
    private javax.swing.JTextField precioc_jfield;
    private javax.swing.JTextField preciov_jfield;
    // End of variables declaration//GEN-END:variables
}
